version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: registration-exercise
    container_name: simple_person
    ports:
    - 8000:80
    volumes:
    - .:/app/